Pruebas unitarias Fernanda.
fernandasanchezg/Entrega3TIS pull request #1
Opened 2020-10-04 17:26 UTC by fernandasanchezg

2020-10-04 17:36 UTC, bastidas6 commented
Fer Hola! Opino que las pruebas estan acordes a las necesidades de la función.

2020-10-04 18:20 UTC, jose0044 requested changes

2020-10-04 18:20 UTC, jose0044 commented on test/EntregaTIS/FuncionFactorialTest.java
> +        // TODO review the generated test code and remove the default call to fail.
Quitar todos los //TODO y los system.out.println de los tests

2020-10-04 18:20 UTC, jose0044 commented on nbproject/project.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Agregar al .gitignore todos los archivos de propiedades del proyecto, solo se versiona codigo fuente, también quitar los .class

2020-10-04 18:33 UTC, fernandasanchezg commented on nbproject/project.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Ya se hicieron los cambios.

2020-10-04 18:34 UTC, fernandasanchezg commented on test/EntregaTIS/FuncionFactorialTest.java
> +        // TODO review the generated test code and remove the default call to fail.
Ya se hicieron los cambios.

2020-10-04 18:35 UTC, jose0044 approved these changes

2020-10-04 21:53 UTC, merged

2020-10-06 00:38 UTC, bastidas6 commented
Muy buen trabajo, los test se entienden con claridad